### ISSUE TITLE
Bug duplicated identifiers for quantiative_feature_value records

### ISSUE THREAD

**Issue by jimmymathews** [nadeemlab/SPT#200]
Encountered the below, triggered by on-demand computation.

```
| 08-24 05:27:23 [  DEBUG  ] workflow.common.export_features:302: Inserting specification 294, data_analysis_study Breast cancer IMC - ondemand computed features
| 08-24 05:27:23 [  DEBUG  ] workflow.common.export_features:316: Inserting specifier: ('294', "(('CK', 'KRT7'), ())", '1')
| 08-24 05:27:23 [  DEBUG  ] workflow.common.export_features:316: Inserting specifier: ('294', "(('CK', 'KRT8KRT18'), ())", '2')
| 08-24 05:27:23 [  DEBUG  ] workflow.common.export_features:316: Inserting specifier: ('294', '100.0', '3')
| 08-24 05:27:23 [  DEBUG  ] workflow.common.cell_df_indexer:36: Some KeyError. (1, 1)
| 08-24 05:27:23 [  DEBUG  ] workflow.common.cell_df_indexer:36: Some KeyError. (1, 1)
| 08-24 05:27:23 [  DEBUG  ] ondemand.providers.pending_provider:85: Number of values possible to be computed: 169
| 08-24 05:27:23 [  DEBUG  ] ondemand.providers.proximity_provider:137: Computed one feature value of 293: BaselTMA_SP43_65_X14Y6, None
| 08-24 05:27:23 [  DEBUG  ] ondemand.providers.pending_provider:111: Actual number computed: 0
| 08-24 05:27:23 [  DEBUG  ] ondemand.providers.pending_provider:37: Not already pending.
| 08-24 05:27:23 [  DEBUG  ] ondemand.providers.pending_provider:39: Starting background task.
| 08-24 05:27:23 [  DEBUG  ] ondemand.providers.pending_provider:42: Background task just started, is pending.
| 08-24 05:27:23 [  DEBUG  ] ondemand.providers.proximity_provider:137: Computed one feature value of 293: BaselTMA_SP43_125_X5Y7, 44.16352201257862
| 08-24 05:27:23 [  DEBUG  ] ondemand.providers.proximity_provider:137: Computed one feature value of 294: BaselTMA_SP43_32_X4Y6, 166.9189189189189
| Exception in thread Thread-35 (have_feature_computed):
| Traceback (most recent call last):
|   File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
|     self.run()
|   File "/usr/local/lib/python3.11/threading.py", line 975, in run
|     self._target(*self._args, **self._kwargs)
|   File "/usr/local/lib/python3.11/site-packages/spatialprofilingtoolbox/ondemand/providers/proximity_provider.py", line 139, in have_feature_computed
|     add_feature_value(feature_specification, sample_identifier, value, cursor)
|   File "/usr/local/lib/python3.11/site-packages/spatialprofilingtoolbox/workflow/common/export_features.py", line 324, in add_feature_value
|     cursor.execute('''
| psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "quantitative_feature_value_pkey"
| DETAIL:  Key (identifier)=(45006) already exists.
```

Most likely the writer of quantitative_feature_value records (I think `ADIFeaturesUploader`) is using some sort of shortcut to assign identifiers for the next record.

For this issue, consider whether such identifiers are even needed. This could be basically "not a problem", solvable by removing the primary key constraint `quantitative_feature_value_pkey`.

**Comment by CarlinLiao** [comment]
I haven't gotten this error. I do suspect the `Some KeyError. (1, 1)` slightly upstream may have something to do with it by selecting incorrect and nonunique values to index with. If we're lucky, it'll be resolved by all the proximity implementation changes in #185.

**Comment by jimmymathews** [comment]
I tried to reproduce using the same triggering query, and there is no error. Probably there was a logic bug early on related to registering new feature identifiers.
